Spring-05
Max-Pochepets/CinemaShop pull request #7
Opened 2021-02-11 12:22 UTC by Max-Pochepets

REST

- Created DTO for CinemaHall, Movie and MovieSession
- Created controller for respective model

2021-02-11 20:55 UTC, Vedroid approved these changes

2021-02-11 20:55 UTC, Vedroid commented on src/main/java/cinema/shop/service/impl/CinemaHallServiceImpl.java
> +                -> new RuntimeException("There is no such cinema hall"));
RuntimeException - Less informative than NoSuchElementException

2021-02-14 19:10 UTC, boroda4436 requested changes

2021-02-14 19:10 UTC, boroda4436 commented on src/main/java/cinema/shop/controller/MovieSessionController.java
> +    public void delete(@RequestBody MovieSessionRequestDto movieSessionRequestDto) {
we should receive an Id of a resource we want to delete
See checklist's link. Try to find an example of `HTTP DELETE http://api.example.com/device-management/managed-devices`

2021-02-14 19:10 UTC, boroda4436 commented on src/main/java/cinema/shop/model/dto/request/MovieSessionRequestDto.java
> +    private Long id;
How we can use it?

2021-02-14 19:10 UTC, boroda4436 commented on src/main/java/cinema/shop/service/impl/CinemaHallServiceImpl.java
> +                -> new RuntimeException("There is no such cinema hall"));
agree

2021-02-15 06:49 UTC, boroda4436 requested changes

2021-02-15 06:49 UTC, boroda4436 commented on src/main/java/cinema/shop/controller/MovieSessionController.java
> +                       @RequestBody MovieSessionRequestDto movieSessionRequestDto) {
Do you still need it?

2021-02-15 09:50 UTC, boroda4436 approved these changes

2021-02-15 22:47 UTC, merged