Spring-06
Max-Pochepets/CinemaShop pull request #9
Opened 2021-02-15 09:45 UTC by Max-Pochepets

Further implementation of Spring MVC

2021-02-15 11:39 UTC, Mandybur800 approved these changes

2021-02-16 12:45 UTC, KseniiaMakarova requested changes

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/controller/AuthenticationController.java
> +@RequestMapping("/")
we can remove this

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/controller/UserController.java
> +            return null;
let's better throw an exception

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/model/dto/response/OrderResponseDto.java
> +    private List<Long> ticketsId;
```suggestion
    private List<Long> ticketIds;
```

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/model/dto/response/ShoppingCartResponseDto.java
> +    private List<Long> ticketsId;
same

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/impl/MovieSessionServiceImpl.java
> +            return null;
let's throw an exception instead

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/impl/MovieServiceImpl.java
> +                -> new NoSuchElementException("There is no such movie."));
let's have the same approach for all the entities maybe?

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/UserResponseMapper.java
> +
remove redundant empty lines - the code is harder to read

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/UserResponseMapper.java
> +    public UserResponseDto toDto(User object) {
```suggestion
    public UserResponseDto toDto(User user) {
```

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/ShoppingCartResponseMapper.java
> +    public ShoppingCartResponseDto toDto(ShoppingCart object) {
same

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/ShoppingCartResponseMapper.java
> +        responseDto.getTicketsId().addAll(object.getTickets().stream()
```suggestion
        responseDto.setTicketIds(object.getTickets().stream()
```

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/OrderResponseMapper.java
> +        responseDto.getTicketsId().addAll(object.getTickets().stream()
same comments here

2021-02-16 12:45 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/OrderResponseMapper.java
> +                                                                .ofPattern("dd.MM.yyyy HH:mm")));
move the pattern to a constant field

2021-02-16 15:40 UTC, KseniiaMakarova requested changes

2021-02-16 15:40 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/controller/AuthenticationController.java
> +@RequestMapping
what is the purpose of this annotation here?

2021-02-16 15:40 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/dto/mapping/impl/response/OrderResponseMapper.java
> +
redundant empty line

2021-02-16 15:40 UTC, KseniiaMakarova commented on src/main/java/cinema/shop/service/impl/MovieSessionServiceImpl.java
> +                -> new NoSuchElementException("Could not get user by id " + id + "."));
why user?

2021-02-16 15:40 UTC, KseniiaMakarova approved these changes
see a few comments above

2021-02-16 16:07 UTC, merged